### ISSUE TITLE
aiotarantool + aiohttp errors

### ISSUE THREAD

**Issue by arusakov** [shveenkov/aiotarantool#13]
I have simple aiohttp + aiotarantool setup (python 3.6.1, tarantool - I try all - 1.6, 1.7, 1.8)

server.py
```python
from aiohttp import web
import aiotarantool


class Handler(object):

    def __init__(self, tnt, space):
        self.tnt = tnt
        self.space = space

    async def get(self, request):
        await self.tnt.select(self.space)
        return web.json_response({})


def main():
    tnt = aiotarantool.connect('127.0.0.1', 3301)

    collectHandler = Handler(tnt, 'tntbench')

    app = web.Application()
    app.router.add_route('GET', '/get', collectHandler.get)
    web.run_app(app, host='0.0.0.0', port=8080)


if __name__ == '__main__':
    main()
```

db.lua
```lua
local DIR = os.getenv('TNTBENCH_DBDIR') or '.db'

pcall(function ()
  os.execute('mkdir ' .. DIR)
end)

box.cfg{
  listen = 3301,
  work_dir = DIR,
}

local function migration001()
  local space = box.schema.space.create('tntbench')
  space:create_index('primary') -- first column as uint as tree

  box.schema.user.grant('guest', 'read,write,execute', 'universe')
end

-- bootstrap
box.once('migration001', migration001)
```

In any scenario in `/get` handler I have an error:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 421, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 303, in _handle
    resp = yield from handler(request)
  File "server/server-simple.py", line 12, in get
    await self.tnt.select(self.space)
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 402, in select
    sp = await self.schema.get_space(space_name)
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 77, in get_space
    array = await self.con.select(tarantool.const.SPACE_SPACE, space, index=_index)
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 410, in select
    RequestSelect(self, space_name, index_name, key, offset, limit, iterator_type))
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 259, in _send_request
    return (await self._send_request_no_check_connected(request))
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 264, in _send_request_no_check_connected
    waiter = self._waiters[sync]
KeyError: None
```

I try select from tarantool via space id - similar error:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 421, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 303, in _handle
    resp = yield from handler(request)
  File "server/server-simple.py", line 12, in get
    await self.tnt.select(self.space)
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 410, in select
    RequestSelect(self, space_name, index_name, key, offset, limit, iterator_type))
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 259, in _send_request
    return (await self._send_request_no_check_connected(request))
  File "/usr/local/lib/python3.6/site-packages/aiotarantool.py", line 264, in _send_request_no_check_connected
    waiter = self._waiters[sync]
KeyError: None
```

The same errro with any other tarantool requests: ping, insert, etc.

**Comment by shveenkov** [comment]
A lot of changes in main tarantool connector,
make woraround for tarantool schema
